@startuml SolarUiSm

' //////////////////////// STATE ORGANIZATION ///////////////////////
' Note: StateSmith treats state names and events as case insensitive.
' More info: https://github.com/StateSmith/StateSmith/wiki/PlantUML

state SPLASH
state HOME



' !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! GEN START !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


state MAIN_MENU {
    [*] -> CURRENT_TIME
    state CURRENT_TIME
    state MAIN_MENU__SOLAR
    state MAIN_MENU__BATTERY

    state SOLAR {
        [*] -> S_VOLTS
        state S_VOLTS
        state S_CURRENT
        state S_POWER
    }
    state BATTERY {
        [*] -> BAT_VOLTS
        state BAT_VOLTS
        state BAT_CURRENT
        state BAT_POWER
        state BATTERY__BAT_ESTIMATE

        state BAT_ESTIMATE {
            [*] -> BTE_TIME_TO_EMPTY
            state BTE_TIME_TO_EMPTY
            state BTE_TIME_TO_FULL
            state BAT_ESTIMATE__BTE_SETTINGS

            state BTE_SETTINGS {
                [*] -> BTE_SETTINGS__BTE_USABLE_PERCENT
                state BTE_SETTINGS__BTE_USABLE_PERCENT
                state BTE_SETTINGS__BTE_WATT_HOURS
                state BTE_SETTINGS__BTE_CHARGE_EFFICIENCY

                state BTE_USABLE_PERCENT {
                    [*] -> BTE_USABLE_PERCENT_EDIT
                    state BTE_USABLE_PERCENT_EDIT
                }
                state BTE_WATT_HOURS {
                    [*] -> BTE_WATT_HOURS_EDIT
                    state BTE_WATT_HOURS_EDIT
                }
                state BTE_CHARGE_EFFICIENCY {
                    [*] -> BTE_CHARGE_EFFICIENCY_EDIT
                    state BTE_CHARGE_EFFICIENCY_EDIT
                }
            }
        }
    }
}

' MAIN_MENU
CURRENT_TIME -down-> MAIN_MENU__SOLAR : DOWN
MAIN_MENU__SOLAR -down-> MAIN_MENU__BATTERY : DOWN
MAIN_MENU__BATTERY -up-> MAIN_MENU__SOLAR : UP
MAIN_MENU__SOLAR -up-> CURRENT_TIME : UP

' SOLAR
MAIN_MENU__SOLAR -right-> SOLAR : RIGHT
SOLAR -left-> MAIN_MENU__SOLAR : LEFT
S_VOLTS -down-> S_CURRENT : DOWN
S_CURRENT -down-> S_POWER : DOWN
S_POWER -up-> S_CURRENT : UP
S_CURRENT -up-> S_VOLTS : UP

' BATTERY
MAIN_MENU__BATTERY -right-> BATTERY : RIGHT
BATTERY -left-> MAIN_MENU__BATTERY : LEFT
BAT_VOLTS -down-> BAT_CURRENT : DOWN
BAT_CURRENT -down-> BAT_POWER : DOWN
BAT_POWER -down-> BATTERY__BAT_ESTIMATE : DOWN
BATTERY__BAT_ESTIMATE -up-> BAT_POWER : UP
BAT_POWER -up-> BAT_CURRENT : UP
BAT_CURRENT -up-> BAT_VOLTS : UP

' BAT_ESTIMATE
BATTERY__BAT_ESTIMATE -right-> BAT_ESTIMATE : RIGHT
BAT_ESTIMATE -left-> BATTERY__BAT_ESTIMATE : LEFT
BTE_TIME_TO_EMPTY -down-> BTE_TIME_TO_FULL : DOWN
BTE_TIME_TO_FULL -down-> BAT_ESTIMATE__BTE_SETTINGS : DOWN
BAT_ESTIMATE__BTE_SETTINGS -up-> BTE_TIME_TO_FULL : UP
BTE_TIME_TO_FULL -up-> BTE_TIME_TO_EMPTY : UP

' BTE_SETTINGS
BAT_ESTIMATE__BTE_SETTINGS -right-> BTE_SETTINGS : RIGHT
BTE_SETTINGS -left-> BAT_ESTIMATE__BTE_SETTINGS : LEFT
BTE_SETTINGS__BTE_USABLE_PERCENT -down-> BTE_SETTINGS__BTE_WATT_HOURS : DOWN
BTE_SETTINGS__BTE_WATT_HOURS -down-> BTE_SETTINGS__BTE_CHARGE_EFFICIENCY : DOWN
BTE_SETTINGS__BTE_CHARGE_EFFICIENCY -up-> BTE_SETTINGS__BTE_WATT_HOURS : UP
BTE_SETTINGS__BTE_WATT_HOURS -up-> BTE_SETTINGS__BTE_USABLE_PERCENT : UP

' BTE_USABLE_PERCENT
BTE_SETTINGS__BTE_USABLE_PERCENT -right-> BTE_USABLE_PERCENT : RIGHT
BTE_USABLE_PERCENT -left-> BTE_SETTINGS__BTE_USABLE_PERCENT : LEFT

' BTE_WATT_HOURS
BTE_SETTINGS__BTE_WATT_HOURS -right-> BTE_WATT_HOURS : RIGHT
BTE_WATT_HOURS -left-> BTE_SETTINGS__BTE_WATT_HOURS : LEFT

' BTE_CHARGE_EFFICIENCY
BTE_SETTINGS__BTE_CHARGE_EFFICIENCY -right-> BTE_CHARGE_EFFICIENCY : RIGHT
BTE_CHARGE_EFFICIENCY -left-> BTE_SETTINGS__BTE_CHARGE_EFFICIENCY : LEFT


'EVENT HANDLERS
MAIN_MENU: enter / menu_header("MAIN MENU");
CURRENT_TIME: enter / show_CURRENT_TIME();
SOLAR: enter / menu_header("SOLAR");
SOLAR: exit / menu_header("MAIN MENU");
MAIN_MENU__SOLAR: enter / option("SOLAR");
S_VOLTS: enter / show_S_VOLTS();
S_CURRENT: enter / show_S_CURRENT();
S_POWER: enter / show_S_POWER();
BATTERY: enter / menu_header("BATTERY");
BATTERY: exit / menu_header("MAIN MENU");
MAIN_MENU__BATTERY: enter / option("BATTERY");
BAT_VOLTS: enter / show_BAT_VOLTS();
BAT_CURRENT: enter / show_BAT_CURRENT();
BAT_POWER: enter / show_BAT_POWER();
BAT_ESTIMATE: enter / menu_header("BAT ESTIMATE");
BAT_ESTIMATE: exit / menu_header("BATTERY");
BATTERY__BAT_ESTIMATE: enter / option("BAT ESTIMATE");
BTE_TIME_TO_EMPTY: enter / show_BTE_TIME_TO_EMPTY();
BTE_TIME_TO_FULL: enter / show_BTE_TIME_TO_FULL();
BTE_SETTINGS: enter / menu_header("BTE SETTINGS");
BTE_SETTINGS: exit / menu_header("BAT ESTIMATE");
BAT_ESTIMATE__BTE_SETTINGS: enter / option("BTE SETTINGS");
BTE_USABLE_PERCENT: enter / menu_header("BTE USABLE PERCENT");
BTE_USABLE_PERCENT: exit / menu_header("BTE SETTINGS");
BTE_SETTINGS__BTE_USABLE_PERCENT: enter / option("BTE USABLE PERCENT");
BTE_USABLE_PERCENT_EDIT: enter / show_BTE_USABLE_PERCENT_EDIT();
BTE_WATT_HOURS: enter / menu_header("BTE WATT HOURS");
BTE_WATT_HOURS: exit / menu_header("BTE SETTINGS");
BTE_SETTINGS__BTE_WATT_HOURS: enter / option("BTE WATT HOURS");
BTE_WATT_HOURS_EDIT: enter / show_BTE_WATT_HOURS_EDIT();
BTE_CHARGE_EFFICIENCY: enter / menu_header("BTE CHARGE EFFICIENCY");
BTE_CHARGE_EFFICIENCY: exit / menu_header("BTE SETTINGS");
BTE_SETTINGS__BTE_CHARGE_EFFICIENCY: enter / option("BTE CHARGE EFFICIENCY");
BTE_CHARGE_EFFICIENCY_EDIT: enter / show_BTE_CHARGE_EFFICIENCY_EDIT();


'MENU POSITION HANDLERS
CURRENT_TIME: enter / menu_at_top();
MAIN_MENU__SOLAR: enter / menu_in_middle();
MAIN_MENU__BATTERY: enter / menu_at_bottom();
S_VOLTS: enter / menu_at_top();
S_CURRENT: enter / menu_in_middle();
S_POWER: enter / menu_at_bottom();
BAT_VOLTS: enter / menu_at_top();
BAT_CURRENT: enter / menu_in_middle();
BAT_POWER: enter / menu_in_middle();
BATTERY__BAT_ESTIMATE: enter / menu_at_bottom();
BTE_TIME_TO_EMPTY: enter / menu_at_top();
BTE_TIME_TO_FULL: enter / menu_in_middle();
BAT_ESTIMATE__BTE_SETTINGS: enter / menu_at_bottom();
BTE_SETTINGS__BTE_USABLE_PERCENT: enter / menu_at_top();
BTE_SETTINGS__BTE_WATT_HOURS: enter / menu_in_middle();
BTE_SETTINGS__BTE_CHARGE_EFFICIENCY: enter / menu_at_bottom();
BTE_USABLE_PERCENT_EDIT: enter / menu_at_top();
BTE_WATT_HOURS_EDIT: enter / menu_at_top();
BTE_CHARGE_EFFICIENCY_EDIT: enter / menu_at_top();



' ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ GEN END ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[*] -> SPLASH

SPLASH -right-> HOME: RIGHT

HOME -right-> MAIN_MENU: RIGHT
MAIN_MENU -left-> HOME: LEFT


SPLASH: enter / show_splash();
HOME: enter / show_home();


' //////////////////////// StateSmith config ////////////////////////
' The below special comment block sets the StateSmith configuration.
' More info: https://github.com/StateSmith/StateSmith/issues/335

/'! $CONFIG : toml
[SmRunnerSettings]
transpilerId = "C99"

[RenderConfig.C]
CFileExtension = ".cpp"
CFileIncludes = """
    #include "display.h"
    """
'/
@enduml